// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIE-Ik9XcLtjOdfDtNbLbUIFNBnVnhK0g',
    appId: '1:1088179544661:web:91abe1bca886e493126adc',
    messagingSenderId: '1088179544661',
    projectId: 'exam-4e678',
    authDomain: 'exam-4e678.firebaseapp.com',
    storageBucket: 'exam-4e678.firebasestorage.app',
    measurementId: 'G-3ZL4GBM2VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL_9OrXiabDMxVexjqbt2c6oVVtDDIxxE',
    appId: '1:1088179544661:android:895d6f2fd2f34331126adc',
    messagingSenderId: '1088179544661',
    projectId: 'exam-4e678',
    storageBucket: 'exam-4e678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUU2lK14-DiVHbDHFoek_j6ofKWb4BTkU',
    appId: '1:1088179544661:ios:9609f28578fe4cd1126adc',
    messagingSenderId: '1088179544661',
    projectId: 'exam-4e678',
    storageBucket: 'exam-4e678.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinelExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUU2lK14-DiVHbDHFoek_j6ofKWb4BTkU',
    appId: '1:1088179544661:ios:9609f28578fe4cd1126adc',
    messagingSenderId: '1088179544661',
    projectId: 'exam-4e678',
    storageBucket: 'exam-4e678.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinelExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIE-Ik9XcLtjOdfDtNbLbUIFNBnVnhK0g',
    appId: '1:1088179544661:web:1de90b00856ff7d1126adc',
    messagingSenderId: '1088179544661',
    projectId: 'exam-4e678',
    authDomain: 'exam-4e678.firebaseapp.com',
    storageBucket: 'exam-4e678.firebasestorage.app',
    measurementId: 'G-1DNRZ2PVJH',
  );
}
